### ISSUE TITLE
Invoke-IcingaCheckClusterHealth - invalid perfdata

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-cluster#23]
Hello,

I found warnings in the logs  regarding invalid perfdata created by CheckClusterHealth:

```
[2021-01-08 14:06:59 +0100] warning/GraphiteWriter: Ignoring invalid perfdata for checkable 'HOSTNAME!Cluster Health' and command 'by_pwsh' with value: cluster_service_status=;;4
Context:
        (0) Processing check result for 'HOSTNAME!Cluster Health'
```

![08-01-_2021_14-10-12](https://user-images.githubusercontent.com/34264690/104019235-7b0b3b80-51bb-11eb-88d3-11d7eae666f3.png)

**Comment by K0nne** [comment]
Sidenote: With JEA we are finally able to monitor the cluster service :)

**Comment by LordHepipud** [comment]
Is this issue still open or was it resolved already?

**Comment by K0nne** [comment]
We don't face it anymore because of JEA, but it is still open. The cluster service is one of those "special secured" services.
