### ISSUE TITLE
Cluster Health - Feature: add a possibility to mitigate the state "paused" as warning instead of critical

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-cluster#25]
Hello,

we whould like to have the ablity to mitigate the state "paused" from "critical" to "warning".

![22-01-_2021_14-13-50](https://user-images.githubusercontent.com/34264690/105495226-35229d00-5cbc-11eb-89c8-96f12ed67e57.png)

According to my coleagues "paused" is a common state, which can happen only due to an admin-interaction. Because of this they whould love to handle it less critical.

**Comment by LordHepipud** [comment]
Thank you for the feature request. Do you want to have an option to switch between Warning/Critical or should be plugin always return Warning only?

**Comment by phinnay** [comment]
A node pause or isolation (assuming you've lumped these states together) can occur in response to events I'd consider critical, depending on the roles hosted on the cluster. Would be good have ability to change between Warning/Critical

**Comment by K0nne** [comment]
Sorry for the late response. Yes, it should be configurable.

**Comment by LordHepipud** [comment]
Can you please test the linked PR for this? We added the filtering for Warning and Critical to the cluster health plugin, allowing you to specify on then the check will throw warning/critical

**Comment by K0nne** [comment]
The PR is working 👍 

Sidenote:
In the docs the new arguments "warningstate" and "criticalstate" are missing.

**Comment by LordHepipud** [comment]
Yes, the docs and new plugin configuration were not created yet. This will be done once I merge the commit.

Thank you for testing!
