### ISSUE TITLE
Feature: Invoke-IcingaCheckClusterSharedVolume - Monitoring of the partition style

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-cluster#28]
Hello,

we whould love to monitor the partition style of our cluster shared volumes to track down something like this:

![03-03-_2021_12-30-20](https://user-images.githubusercontent.com/34264690/109799439-590ec200-7c1c-11eb-94b7-e8314bf223fc.png)

It whould be great if the target partition style were an configurable option.

Thanks :)

**Comment by K0nne** [comment]
I found a way to correlate data between `get-clustersharedvolume` and `get-disk`. With this it is possible to get the partitonstyle for a given LUN:

```
$csv_name = (get-clustersharedvolume "%VOLUME_NAME%").SharedvolumeInfo.Partition.Name
$disk_id = (get-partition | where-object -property accesspaths -contains $csv_name).diskid
$partition_style = (get-disk | where-object -property path -eq $disk_id).partitionstyle
$partition_style
```
GPT

**Comment by LordHepipud** [comment]
Can you please test the linked PR? I tried to implement this feature but have no system with Cluster Shared Volumes to my hand.
There is no argument which can be configured. It only checks the partition space and compares it to `RAW` and reports critical in that case.

**Comment by K0nne** [comment]
Thank you for the PR. I will report back!
