### ISSUE TITLE
Invoke-IcingaCheckClusterSharedVolume - This argument does not support the % unit

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-cluster#36]
Hello,

we are trying to set thresholds for the check Invoke-IcingaCheckClusterSharedVolume. According to the [docs ](https://github.com/Icinga/icinga-powershell-cluster/blob/master/doc/plugins/02-Invoke-IcingaCheckClusterSharedVolume.md) "SpaceWarning" and "SpaceCritical" can be defined with percentage unit, but it seems this is not supported yet.

```
*******************************************
**       Icinga for Windows v1.7.1       **
** Copyright (c) 2021 Icinga GmbH | MIT  **
** User environment                      **
*******************************************
icinga> Invoke-IcingaCheckClusterSharedVolume -Spacewarning 80% -SpaceCritical 90% -Verbosity 3

[UNKNOWN] Network Volumes Package: 3 Unknown 1 Ok [UNKNOWN] SharedVolume LUN002, SharedVolume LUN003, SharedVolume Test04 (All must be [OK])
\_ [OK] Cluster Resource Package (All must be [OK])
   \_ [OK] LUN001 Status: Online
   \_ [OK] Storage Qos Resource Status: Online
\_ [UNKNOWN] SharedVolume LUN002 (All must be [OK])
   \_ [OK] LUN002 Fault State: NoFaults
   \_ [OK] LUN002 State: Online
   \_ [UNKNOWN] LUN002 Used Space: This argument does not support the % unit
[...]
```

![2021-11-30_08-54-51](https://user-images.githubusercontent.com/34264690/144009913-d70b3b66-d6fb-4e0d-8f91-1502942cbfdc.png)

We are using the latest cluster_bundle.conf as command definition.

**Comment by aheinhold** [comment]
Hallo @LordHepipud 
Is it possible to add the support of threshold values in percent for this check?

**Comment by aheinhold** [comment]
Hi, i tested the PR and it works. We can now set %-thresholds.
