### ISSUE TITLE
Invoke-IcingaCheckHyperVOvercommitment: Detection of installed cluster-plugins not working

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-cluster#40]
Hello,

we use the latest releases of all modules. In one case the overcommitment-check produces a warning, because it cant detect die cluster-module. 

The thing is, the cluster-module is installed and working ^^

![image](https://user-images.githubusercontent.com/34264690/168032289-d173c301-27c0-4b91-99df-d1744ceb5aaf.png)

**Comment by LordHepipud** [comment]
Can you please test the linked PR? This should resolve the issue.
An update for the Cluster plugins is required in this case.

**Comment by K0nne** [comment]
The PR is working. The warning message is gone. 
Also the (possibly false) detected overcommitment of c: is gone. This aspect was bugging the hypverv colleagues before.

**before:**  
![image](https://user-images.githubusercontent.com/34264690/168048157-5d7cb62a-52c9-4738-9276-d3298377148e.png)

**after:**  
![image](https://user-images.githubusercontent.com/34264690/168048225-17e0ce3f-db27-4281-81f7-fa173486080e.png)

**Comment by LordHepipud** [comment]
That `CRITICAL` error occurs because the calculation is off probably, because the cluster information couldn't be read and therefore an invalid base value was used.

I will merge the PR and tag the v1.1.1 of the cluster plugins.
