### ISSUE TITLE
Invoke-IcingaCheckClusterSharedVolume: No checks added to this package

### ISSUE THREAD

**Issue by Lprod** [Icinga/icinga-powershell-cluster#48]
Hello,

this issue has arisen from the support case #784384.
We have distributed the check IcingaCheckClusterSharedVolume on several clusters via template and unfortunately found out that the check does not run correctly on certain clusters and outputs an unkown.

![IcingaCheckClusterSharedVolume](https://github.com/Icinga/icinga-powershell-cluster/assets/91473467/583f0d57-8029-479c-9bc4-6c1815d091de)

After a lengthy search with support, among others, we found that the check only runs if at least one disk explicitly marked as "Cluster Shared Volume" is present on the system. If this is the case, this and all other cluster disks are monitored. If this is not the case, the check returns an Unkown and none of the cluster disks are monitored.

In our view, this means that an important functionality is missing from the existing cluster checks, as cluster disk monitoring has not been considered in its entirety. One could either extend Invoke-IcingaCheckClusterSharedVolume so that it also runs if there is no explicit marking of a disk with "Cluster Shared Volume" or develop a general cluster disk plugin.
We would be happy to demonstrate the problems we currently have with this in a live demo and explain what exactly we would expect from such a check, if this is desired.

Details:
icinga-powershell-framework: 1.10.1
icinga-powershell-plugins: 1.10.1
icinga-powershell-cluster: 1.2.0

**Comment by carraroj** [comment]
ref/NC/784384

**Comment by Lprod** [comment]
Solution: https://github.com/Icinga/icinga-powershell-cluster/pull/50
